export const quotes: string[] = [
  '"It’s time for you to look inward and start asking yourself the big question: who are you and what do you want?"',
  '"Are you so busy fighting you cannot see your own ship has set sail?"',
  '"It is important to draw wisdom from different places. If you take it from only one place it becomes rigid and stale."',
  '"Sometimes life is like this dark tunnel, you can’t always see the light at the end of the tunnel, but if you just keep moving, you will come to a better place."',
  '"It is usually best to admit mistakes when they occur, and to seek to restore honor."',
  '"There is nothing wrong with letting people who love you, help you. Not that I love you. I just met you."',
  '"I know you’re not supposed to cry over spilled tea, but it’s just so sad!"',
  '"Sometimes, the best way to solve your own problems is to help someone else."',
  '"In the darkest times, Hope is something that you give yourself. That is the meaning of inner strength."',
  '"Pride is not the opposite of shame, but its source. True humility is the only antidote to shame."',
  '"You must never give into dispair. Allow yourself to slip down that road and you surrender to your lowest instincts."',
  '"You sound like my nephew. Always thinking you need to do things on your own without anyone\'s support."',
  '"You never know how things are going to work out. But if you keep an open mind and an open heart, I promise you will find your own destiny someday."',
  '"There\'s nothing wrong with a life of peace and prosperity."',
  '"I suggest you think about what it is that you want from your life, and why."',
  '"You have light and peace inside of you. If you let it out, you can change the world around you."',
  '"Many things that seem threatening in the dark become welcoming when we shine light on them."',
  '"You will find that if you look for the light, you can often find it. But if you look for the dark, that is all you will ever see."',
  '"You are stronger and wiser and freer than you ever used to be."',
  '"Protection and power are overrated. I think you are very wise to choose happiness and love."',
  '"Failure is only the opportunity to begin again. Only this time, more wisely."',
  '"Good times become good memories, but bad times become good lessons."',
  '"While it is always best to believe in one’s self, a little help from others can be a great blessing."',
  '"It’s time for you to choose. It’s time for you to choose good."'
];
